doctrine:
    dbal:
        default_connection: shard_one
        connections:
            shard_one:
                url: '%env(resolve:DATABASE_URL_SHARD_ONE)%'
            shard_two:
                url: '%env(resolve:DATABASE_URL_SHARD_TWO)%'


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        default_entity_manager: shard_one
        auto_generate_proxy_classes: true

        entity_managers:
            shard_one:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: shard_one
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/ShardOne'
                        prefix: 'App\Entity'
                        alias: App
            shard_two:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: shard_two
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/ShardTwo'
                        prefix: 'App\Entity'
                        alias: App
